// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vb_aIwml6tiBNrWnQtr-5r01TcEmvX4',
    appId: '1:182498288863:web:18422b1ea6401c1db6f56a',
    messagingSenderId: '182498288863',
    projectId: 'productdetailapp-5cb63',
    authDomain: 'productdetailapp-5cb63.firebaseapp.com',
    storageBucket: 'productdetailapp-5cb63.firebasestorage.app',
    measurementId: 'G-YR7LF907T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_r-AuOL5THOmRW3FjDb5qO18D6Nfl6Y8',
    appId: '1:182498288863:android:627f628b6e8f092fb6f56a',
    messagingSenderId: '182498288863',
    projectId: 'productdetailapp-5cb63',
    storageBucket: 'productdetailapp-5cb63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7bLgEjNkTTw4kn4jMmaNK7E7-5e3WS2U',
    appId: '1:182498288863:ios:73883dea1fdaf9ebb6f56a',
    messagingSenderId: '182498288863',
    projectId: 'productdetailapp-5cb63',
    storageBucket: 'productdetailapp-5cb63.firebasestorage.app',
    iosBundleId: 'com.example.productDetailApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7bLgEjNkTTw4kn4jMmaNK7E7-5e3WS2U',
    appId: '1:182498288863:ios:73883dea1fdaf9ebb6f56a',
    messagingSenderId: '182498288863',
    projectId: 'productdetailapp-5cb63',
    storageBucket: 'productdetailapp-5cb63.firebasestorage.app',
    iosBundleId: 'com.example.productDetailApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8vb_aIwml6tiBNrWnQtr-5r01TcEmvX4',
    appId: '1:182498288863:web:ea7b2558337156a5b6f56a',
    messagingSenderId: '182498288863',
    projectId: 'productdetailapp-5cb63',
    authDomain: 'productdetailapp-5cb63.firebaseapp.com',
    storageBucket: 'productdetailapp-5cb63.firebasestorage.app',
    measurementId: 'G-CBT5DE9YWG',
  );
}
